"""empty message

Revision ID: dcf2c2053c5b
Revises: 
Create Date: 2018-02-06 10:53:38.758168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf2c2053c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('location_alias', sa.String(length=30), nullable=True),
    sa.Column('coordinate', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coordinate')
    )
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
